# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spire.api.types import selector_pb2 as spire_dot_api_dot_types_dot_selector__pb2
from spire.api.types import spiffeid_pb2 as spire_dot_api_dot_types_dot_spiffeid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bspire/api/types/agent.proto\x12\x0fspire.api.types\x1a\x1espire/api/types/selector.proto\x1a\x1espire/api/types/spiffeid.proto\"\xc3\x01\n\x05\x41gent\x12%\n\x02id\x18\x01 \x01(\x0b\x32\x19.spire.api.types.SPIFFEID\x12\x18\n\x10\x61ttestation_type\x18\x02 \x01(\t\x12\x1e\n\x16x509svid_serial_number\x18\x03 \x01(\t\x12\x1b\n\x13x509svid_expires_at\x18\x04 \x01(\x03\x12,\n\tselectors\x18\x05 \x03(\x0b\x32\x19.spire.api.types.Selector\x12\x0e\n\x06\x62\x61nned\x18\x06 \x01(\x08\"\x85\x01\n\tAgentMask\x12\x18\n\x10\x61ttestation_type\x18\x02 \x01(\x08\x12\x1e\n\x16x509svid_serial_number\x18\x03 \x01(\x08\x12\x1b\n\x13x509svid_expires_at\x18\x04 \x01(\x08\x12\x11\n\tselectors\x18\x05 \x01(\x08\x12\x0e\n\x06\x62\x61nned\x18\x06 \x01(\x08\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_AGENT = DESCRIPTOR.message_types_by_name['Agent']
_AGENTMASK = DESCRIPTOR.message_types_by_name['AgentMask']
Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), {
  'DESCRIPTOR' : _AGENT,
  '__module__' : 'spire.api.types.agent_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.Agent)
  })
_sym_db.RegisterMessage(Agent)

AgentMask = _reflection.GeneratedProtocolMessageType('AgentMask', (_message.Message,), {
  'DESCRIPTOR' : _AGENTMASK,
  '__module__' : 'spire.api.types.agent_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.AgentMask)
  })
_sym_db.RegisterMessage(AgentMask)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _AGENT._serialized_start=113
  _AGENT._serialized_end=308
  _AGENTMASK._serialized_start=311
  _AGENTMASK._serialized_end=444
# @@protoc_insertion_point(module_scope)
