# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/attestation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!spire/api/types/attestation.proto\x12\x0fspire.api.types\"0\n\x0f\x41ttestationData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_ATTESTATIONDATA = DESCRIPTOR.message_types_by_name['AttestationData']
AttestationData = _reflection.GeneratedProtocolMessageType('AttestationData', (_message.Message,), {
  'DESCRIPTOR' : _ATTESTATIONDATA,
  '__module__' : 'spire.api.types.attestation_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.AttestationData)
  })
_sym_db.RegisterMessage(AttestationData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _ATTESTATIONDATA._serialized_start=54
  _ATTESTATIONDATA._serialized_end=102
# @@protoc_insertion_point(module_scope)
