# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/entry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spire.api.types import selector_pb2 as spire_dot_api_dot_types_dot_selector__pb2
from spire.api.types import spiffeid_pb2 as spire_dot_api_dot_types_dot_spiffeid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bspire/api/types/entry.proto\x12\x0fspire.api.types\x1a\x1espire/api/types/selector.proto\x1a\x1espire/api/types/spiffeid.proto\"\xb9\x02\n\x05\x45ntry\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\tspiffe_id\x18\x02 \x01(\x0b\x32\x19.spire.api.types.SPIFFEID\x12,\n\tparent_id\x18\x03 \x01(\x0b\x32\x19.spire.api.types.SPIFFEID\x12,\n\tselectors\x18\x04 \x03(\x0b\x32\x19.spire.api.types.Selector\x12\x0b\n\x03ttl\x18\x05 \x01(\x05\x12\x16\n\x0e\x66\x65\x64\x65rates_with\x18\x06 \x03(\t\x12\r\n\x05\x61\x64min\x18\x07 \x01(\x08\x12\x12\n\ndownstream\x18\x08 \x01(\x08\x12\x12\n\nexpires_at\x18\t \x01(\x03\x12\x11\n\tdns_names\x18\n \x03(\t\x12\x17\n\x0frevision_number\x18\x0b \x01(\x03\x12\x12\n\nstore_svid\x18\x0c \x01(\x08\"\xe0\x01\n\tEntryMask\x12\x11\n\tspiffe_id\x18\x02 \x01(\x08\x12\x11\n\tparent_id\x18\x03 \x01(\x08\x12\x11\n\tselectors\x18\x04 \x01(\x08\x12\x0b\n\x03ttl\x18\x05 \x01(\x08\x12\x16\n\x0e\x66\x65\x64\x65rates_with\x18\x06 \x01(\x08\x12\r\n\x05\x61\x64min\x18\x07 \x01(\x08\x12\x12\n\ndownstream\x18\x08 \x01(\x08\x12\x12\n\nexpires_at\x18\t \x01(\x08\x12\x11\n\tdns_names\x18\n \x01(\x08\x12\x17\n\x0frevision_number\x18\x0b \x01(\x08\x12\x12\n\nstore_svid\x18\x0c \x01(\x08\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_ENTRY = DESCRIPTOR.message_types_by_name['Entry']
_ENTRYMASK = DESCRIPTOR.message_types_by_name['EntryMask']
Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
  'DESCRIPTOR' : _ENTRY,
  '__module__' : 'spire.api.types.entry_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.Entry)
  })
_sym_db.RegisterMessage(Entry)

EntryMask = _reflection.GeneratedProtocolMessageType('EntryMask', (_message.Message,), {
  'DESCRIPTOR' : _ENTRYMASK,
  '__module__' : 'spire.api.types.entry_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.EntryMask)
  })
_sym_db.RegisterMessage(EntryMask)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _ENTRY._serialized_start=113
  _ENTRY._serialized_end=426
  _ENTRYMASK._serialized_start=429
  _ENTRYMASK._serialized_end=653
# @@protoc_insertion_point(module_scope)
