# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/federateswith.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#spire/api/types/federateswith.proto\x12\x0fspire.api.types\"\xc4\x01\n\x12\x46\x65\x64\x65ratesWithMatch\x12\x15\n\rtrust_domains\x18\x01 \x03(\t\x12@\n\x05match\x18\x02 \x01(\x0e\x32\x31.spire.api.types.FederatesWithMatch.MatchBehavior\"U\n\rMatchBehavior\x12\x0f\n\x0bMATCH_EXACT\x10\x00\x12\x10\n\x0cMATCH_SUBSET\x10\x01\x12\x12\n\x0eMATCH_SUPERSET\x10\x02\x12\r\n\tMATCH_ANY\x10\x03\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_FEDERATESWITHMATCH = DESCRIPTOR.message_types_by_name['FederatesWithMatch']
_FEDERATESWITHMATCH_MATCHBEHAVIOR = _FEDERATESWITHMATCH.enum_types_by_name['MatchBehavior']
FederatesWithMatch = _reflection.GeneratedProtocolMessageType('FederatesWithMatch', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATESWITHMATCH,
  '__module__' : 'spire.api.types.federateswith_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.FederatesWithMatch)
  })
_sym_db.RegisterMessage(FederatesWithMatch)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _FEDERATESWITHMATCH._serialized_start=57
  _FEDERATESWITHMATCH._serialized_end=253
  _FEDERATESWITHMATCH_MATCHBEHAVIOR._serialized_start=168
  _FEDERATESWITHMATCH_MATCHBEHAVIOR._serialized_end=253
# @@protoc_insertion_point(module_scope)
