# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/federationrelationship.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spire.api.types import bundle_pb2 as spire_dot_api_dot_types_dot_bundle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,spire/api/types/federationrelationship.proto\x12\x0fspire.api.types\x1a\x1cspire/api/types/bundle.proto\"\x90\x02\n\x16\x46\x65\x64\x65rationRelationship\x12\x14\n\x0ctrust_domain\x18\x01 \x01(\t\x12\x1b\n\x13\x62undle_endpoint_url\x18\x02 \x01(\t\x12\x35\n\thttps_web\x18\x03 \x01(\x0b\x32 .spire.api.types.HTTPSWebProfileH\x00\x12;\n\x0chttps_spiffe\x18\x04 \x01(\x0b\x32#.spire.api.types.HTTPSSPIFFEProfileH\x00\x12\x34\n\x13trust_domain_bundle\x18\x05 \x01(\x0b\x32\x17.spire.api.types.BundleB\x19\n\x17\x62undle_endpoint_profile\"0\n\x12HTTPSSPIFFEProfile\x12\x1a\n\x12\x65ndpoint_spiffe_id\x18\x01 \x01(\t\"\x11\n\x0fHTTPSWebProfile\"w\n\x1a\x46\x65\x64\x65rationRelationshipMask\x12\x1b\n\x13\x62undle_endpoint_url\x18\x01 \x01(\x08\x12\x1f\n\x17\x62undle_endpoint_profile\x18\x02 \x01(\x08\x12\x1b\n\x13trust_domain_bundle\x18\x03 \x01(\x08\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_FEDERATIONRELATIONSHIP = DESCRIPTOR.message_types_by_name['FederationRelationship']
_HTTPSSPIFFEPROFILE = DESCRIPTOR.message_types_by_name['HTTPSSPIFFEProfile']
_HTTPSWEBPROFILE = DESCRIPTOR.message_types_by_name['HTTPSWebProfile']
_FEDERATIONRELATIONSHIPMASK = DESCRIPTOR.message_types_by_name['FederationRelationshipMask']
FederationRelationship = _reflection.GeneratedProtocolMessageType('FederationRelationship', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATIONRELATIONSHIP,
  '__module__' : 'spire.api.types.federationrelationship_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.FederationRelationship)
  })
_sym_db.RegisterMessage(FederationRelationship)

HTTPSSPIFFEProfile = _reflection.GeneratedProtocolMessageType('HTTPSSPIFFEProfile', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSSPIFFEPROFILE,
  '__module__' : 'spire.api.types.federationrelationship_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.HTTPSSPIFFEProfile)
  })
_sym_db.RegisterMessage(HTTPSSPIFFEProfile)

HTTPSWebProfile = _reflection.GeneratedProtocolMessageType('HTTPSWebProfile', (_message.Message,), {
  'DESCRIPTOR' : _HTTPSWEBPROFILE,
  '__module__' : 'spire.api.types.federationrelationship_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.HTTPSWebProfile)
  })
_sym_db.RegisterMessage(HTTPSWebProfile)

FederationRelationshipMask = _reflection.GeneratedProtocolMessageType('FederationRelationshipMask', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATIONRELATIONSHIPMASK,
  '__module__' : 'spire.api.types.federationrelationship_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.FederationRelationshipMask)
  })
_sym_db.RegisterMessage(FederationRelationshipMask)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _FEDERATIONRELATIONSHIP._serialized_start=96
  _FEDERATIONRELATIONSHIP._serialized_end=368
  _HTTPSSPIFFEPROFILE._serialized_start=370
  _HTTPSSPIFFEPROFILE._serialized_end=418
  _HTTPSWEBPROFILE._serialized_start=420
  _HTTPSWEBPROFILE._serialized_end=437
  _FEDERATIONRELATIONSHIPMASK._serialized_start=439
  _FEDERATIONRELATIONSHIPMASK._serialized_end=558
# @@protoc_insertion_point(module_scope)
