# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/selector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espire/api/types/selector.proto\x12\x0fspire.api.types\"\'\n\x08Selector\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xd1\x01\n\rSelectorMatch\x12,\n\tselectors\x18\x01 \x03(\x0b\x32\x19.spire.api.types.Selector\x12;\n\x05match\x18\x02 \x01(\x0e\x32,.spire.api.types.SelectorMatch.MatchBehavior\"U\n\rMatchBehavior\x12\x0f\n\x0bMATCH_EXACT\x10\x00\x12\x10\n\x0cMATCH_SUBSET\x10\x01\x12\x12\n\x0eMATCH_SUPERSET\x10\x02\x12\r\n\tMATCH_ANY\x10\x03\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_SELECTOR = DESCRIPTOR.message_types_by_name['Selector']
_SELECTORMATCH = DESCRIPTOR.message_types_by_name['SelectorMatch']
_SELECTORMATCH_MATCHBEHAVIOR = _SELECTORMATCH.enum_types_by_name['MatchBehavior']
Selector = _reflection.GeneratedProtocolMessageType('Selector', (_message.Message,), {
  'DESCRIPTOR' : _SELECTOR,
  '__module__' : 'spire.api.types.selector_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.Selector)
  })
_sym_db.RegisterMessage(Selector)

SelectorMatch = _reflection.GeneratedProtocolMessageType('SelectorMatch', (_message.Message,), {
  'DESCRIPTOR' : _SELECTORMATCH,
  '__module__' : 'spire.api.types.selector_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.SelectorMatch)
  })
_sym_db.RegisterMessage(SelectorMatch)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _SELECTOR._serialized_start=51
  _SELECTOR._serialized_end=90
  _SELECTORMATCH._serialized_start=93
  _SELECTORMATCH._serialized_end=302
  _SELECTORMATCH_MATCHBEHAVIOR._serialized_start=217
  _SELECTORMATCH_MATCHBEHAVIOR._serialized_end=302
# @@protoc_insertion_point(module_scope)
