# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/spiffeid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espire/api/types/spiffeid.proto\x12\x0fspire.api.types\".\n\x08SPIFFEID\x12\x14\n\x0ctrust_domain\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\tB7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_SPIFFEID = DESCRIPTOR.message_types_by_name['SPIFFEID']
SPIFFEID = _reflection.GeneratedProtocolMessageType('SPIFFEID', (_message.Message,), {
  'DESCRIPTOR' : _SPIFFEID,
  '__module__' : 'spire.api.types.spiffeid_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.SPIFFEID)
  })
_sym_db.RegisterMessage(SPIFFEID)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _SPIFFEID._serialized_start=51
  _SPIFFEID._serialized_end=97
# @@protoc_insertion_point(module_scope)
