# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cspire/api/types/status.proto\x12\x0fspire.api.types\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc4\x01\n\x17PermissionDeniedDetails\x12?\n\x06reason\x18\x01 \x01(\x0e\x32/.spire.api.types.PermissionDeniedDetails.Reason\"h\n\x06Reason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rAGENT_EXPIRED\x10\x01\x12\x16\n\x12\x41GENT_NOT_ATTESTED\x10\x02\x12\x14\n\x10\x41GENT_NOT_ACTIVE\x10\x03\x12\x10\n\x0c\x41GENT_BANNED\x10\x04\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_STATUS = DESCRIPTOR.message_types_by_name['Status']
_PERMISSIONDENIEDDETAILS = DESCRIPTOR.message_types_by_name['PermissionDeniedDetails']
_PERMISSIONDENIEDDETAILS_REASON = _PERMISSIONDENIEDDETAILS.enum_types_by_name['Reason']
Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'spire.api.types.status_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.Status)
  })
_sym_db.RegisterMessage(Status)

PermissionDeniedDetails = _reflection.GeneratedProtocolMessageType('PermissionDeniedDetails', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONDENIEDDETAILS,
  '__module__' : 'spire.api.types.status_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.PermissionDeniedDetails)
  })
_sym_db.RegisterMessage(PermissionDeniedDetails)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _STATUS._serialized_start=49
  _STATUS._serialized_end=88
  _PERMISSIONDENIEDDETAILS._serialized_start=91
  _PERMISSIONDENIEDDETAILS._serialized_end=287
  _PERMISSIONDENIEDDETAILS_REASON._serialized_start=183
  _PERMISSIONDENIEDDETAILS_REASON._serialized_end=287
# @@protoc_insertion_point(module_scope)
