# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spire/api/types/x509svid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spire.api.types import spiffeid_pb2 as spire_dot_api_dot_types_dot_spiffeid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espire/api/types/x509svid.proto\x12\x0fspire.api.types\x1a\x1espire/api/types/spiffeid.proto\"Y\n\x08X509SVID\x12\x12\n\ncert_chain\x18\x01 \x03(\x0c\x12%\n\x02id\x18\x02 \x01(\x0b\x32\x19.spire.api.types.SPIFFEID\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\x42\x37Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3')



_X509SVID = DESCRIPTOR.message_types_by_name['X509SVID']
X509SVID = _reflection.GeneratedProtocolMessageType('X509SVID', (_message.Message,), {
  'DESCRIPTOR' : _X509SVID,
  '__module__' : 'spire.api.types.x509svid_pb2'
  # @@protoc_insertion_point(class_scope:spire.api.types.X509SVID)
  })
_sym_db.RegisterMessage(X509SVID)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/spiffe/spire-api-sdk/proto/spire/api/types'
  _X509SVID._serialized_start=83
  _X509SVID._serialized_end=172
# @@protoc_insertion_point(module_scope)
