# permissions for end users to view floperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floperator-viewer-role
rules:
- apiGroups:
  - fl.katulu.io
  resources:
  - floperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fl.katulu.io
  resources:
  - floperators/status
  verbs:
  - get
