---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OIDC Authservice
  - ../../../components/vendor/kubeflow-manifests/common/oidc-authservice/base
  # Dex
  - ../../../components/katulu-dex
  # Kubeflow namespace
  - ../../../components/vendor/kubeflow-manifests/common/kubeflow-namespace/base
  # Kubeflow Roles
  - ../../../components/vendor/kubeflow-manifests/common/kubeflow-roles/base
  # Kubeflow Istio Resources
  - ../../../components/vendor/kubeflow-manifests/common/istio-1-11/kubeflow-istio-resources/base

  # Kubeflow Pipelines
  - ../../../components/vendor/kubeflow-manifests/apps/pipeline/upstream/env/platform-agnostic-multi-user-emissary
  # Central Dashboard
  - ../../../components/centraldashboard
  # Profiles + KFAM
  - ../../../components/vendor/kubeflow-manifests/apps/profiles/upstream/overlays/kubeflow
  # User namespace
  - ../../../components/kubeflow-profile/kustomize
  # Edges Web app
  # The edge-identity manifests deploy spire-server. This is because the edge-identity needs to live along side the spire-server container to get admin access
  - ../../../components/edge-identity/kustomize/overlays/istio

  # Container registry
  - ../../../components/container-registry/kustomize/overlays/kubeflow

  # Spire
  - ../../../components/spire/kustomize/spire-namespace
  - ../../../components/spire/kustomize/spire-agent

  - ../../../components/kubeflow-notebooks
  - ../../../components/kubeflow-pipeline/kustomize
  - ../../../components/fl-orchestrator
  - ../../../components/client-image-builder/kustomize

patches:
  # This patch (kustomize patch) is here to use mysql 8.0 which prevents really
  # high memory usage (https://github.com/docker-library/mysql/issues/579) in
  # environments with nofile set to infinity or too high. This patch can be
  # discarded once https://github.com/kubeflow/pipelines/pull/5946 is merged
  # into kubeflow.
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: gcr.io/ml-pipeline/mysql:8.0
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --default-authentication-plugin=mysql_native_password
          - --datadir
          - /var/lib/mysql
    target:
      name: mysql
      namespace: kubeflow
      kind: Deployment
      group: apps
      version: v1
