---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OIDC Authservice
  - ../../../components/vendor/kubeflow/common/oidc-authservice/base
  # Dex
  - ../../../components/katulu-dex
  # KNative
  - ../../../components/vendor/kubeflow/common/knative/knative-serving/overlays/gateways
  - ../../../components/vendor/kubeflow/common/knative/knative-eventing/base
  - ../../../components/vendor/kubeflow/common/istio-1-11/cluster-local-gateway/base
  # Kubeflow namespace
  - ../../../components/vendor/kubeflow/common/kubeflow-namespace/base
  # Kubeflow Roles
  - ../../../components/vendor/kubeflow/common/kubeflow-roles/base
  # Kubeflow Istio Resources
  - ../../../components/vendor/kubeflow/common/istio-1-11/kubeflow-istio-resources/base

  # Kubeflow Pipelines
  - ../../../components/vendor/kubeflow/apps/pipeline/upstream/env/platform-agnostic-multi-user-emissary
  # Central Dashboard
  - ../../../components/centraldashboard
  # Admission Webhook
  - ../../../components/vendor/kubeflow/apps/admission-webhook/upstream/overlays/cert-manager
  # Notebook Controller
  - ../../../components/vendor/kubeflow/apps/jupyter/jupyter-web-app/upstream/overlays/istio
  # Jupyter Web App
  - ../../../components/vendor/kubeflow/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  # Profiles + KFAM
  - ../../../components/vendor/kubeflow/apps/profiles/upstream/overlays/kubeflow
  # Volumes Web App
  - ../../../components/vendor/kubeflow/apps/volumes-web-app/upstream/overlays/istio
  # Training Operator
  - ../../../components/vendor/kubeflow/apps/training-operator/upstream/overlays/kubeflow
  # User namespace
  - ../../../components/kubeflow-profile/kustomize

  # Container registry
  - ../../../components/container-registry/kustomize

  # Spire
  - ../../../components/spire/kustomize/spire-namespace
  - ../../../components/spire/kustomize/spire-server
  - ../../../components/spire/kustomize/spire-agent

  - ../../../components/kubeflow-notebooks/kustomize
  - ../../../components/kubeflow-pipeline/kustomize
  - ../../../components/fl-orchestrator
  - ../../../components/client-image-builder/kustomize
