apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
namespace: kubeflow
commonLabels:
  app: edges-web-app
  kustomize.component: edges-web-app
