apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edges-web-app-edges-web-app
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /edges
    match:
    - uri:
        prefix: /edges/
    rewrite:
      uri: /
    route:
    - destination:
        host: edges-web-app-service.kubeflow.svc.cluster.local
        port:
          number: 80
