---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: flower-server-envoyproxy
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "katulu-fl/*"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
