apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace created by the katulu-fl profile. A retry is required to create the resources inside the katulu-fl namespace because the katulu-fl might not be created immediately.
namespace: katulu-fl

resources:
- envoyproxy-gateway.yaml
