apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../vendor/kubeflow-manifests/common/dex/overlays/istio
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: katulu-dex
    target:
      group: apps
      version: v1
      kind: Deployment
      name: dex
