apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fl-orchestrator
subjects:
  - kind: ServiceAccount
    name: fl-orchestrator
    namespace: katulu-fl
roleRef:
  kind: ClusterRole
  name: kubeflow-pipelines-view
  apiGroup: rbac.authorization.k8s.io
