CREATE TABLE IF NOT EXISTS Edge (
	edge_id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	namespace TEXT NOT NULL,
	created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS JoinTokenAuth (
	join_token TEXT NOT NULL,
	edge_id INTEGER,
	CONSTRAINT fk_edge
		FOREIGN KEY (edge_id)
		REFERENCES Edge(edge_id)
		ON DELETE CASCADE
);
