# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from spire.api.server.agent.v1 import agent_pb2 as spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2
from spire.api.types import agent_pb2 as spire_dot_api_dot_types_dot_agent__pb2
from spire.api.types import jointoken_pb2 as spire_dot_api_dot_types_dot_jointoken__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountAgents = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/CountAgents',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsResponse.FromString,
                )
        self.ListAgents = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/ListAgents',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsResponse.FromString,
                )
        self.GetAgent = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/GetAgent',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_types_dot_agent__pb2.Agent.FromString,
                )
        self.DeleteAgent = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/DeleteAgent',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.BanAgent = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/BanAgent',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.BanAgentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.AttestAgent = channel.stream_stream(
                '/spire.api.server.agent.v1.Agent/AttestAgent',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentResponse.FromString,
                )
        self.RenewAgent = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/RenewAgent',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentResponse.FromString,
                )
        self.CreateJoinToken = channel.unary_unary(
                '/spire.api.server.agent.v1.Agent/CreateJoinToken',
                request_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CreateJoinTokenRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_types_dot_jointoken__pb2.JoinToken.FromString,
                )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountAgents(self, request, context):
        """Count agents.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Lists agents.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Gets an agent.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Deletes an agent. The agent can come back into the trust domain through
        the Issuer AttestAgent RPC.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BanAgent(self, request, context):
        """Bans an agent. This evicts the agent and prevents it from rejoining the
        trust domain through attestation until the ban is lifted via a call to
        DeleteAgent.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttestAgent(self, request_iterator, context):
        """Attests the agent via node attestation, using a bidirectional stream to
        faciliate attestation methods that require challenge/response.

        The caller is not authenticated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewAgent(self, request, context):
        """Renews the agent and returns a new X509-SVID. The new SVID is not enabled
        on the server side until its first use.

        The caller must present an active agent X509-SVID, i.e. the X509-SVID
        returned by the AttestAgent or the most recent RenewAgent call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJoinToken(self, request, context):
        """Creates an agent join token. The token can be used with `join_token`
        attestation to join the trust domain.

        The caller must be local or present an admin X509-SVID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.CountAgents,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsRequest.FromString,
                    response_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsRequest.FromString,
                    response_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.GetAgentRequest.FromString,
                    response_serializer=spire_dot_api_dot_types_dot_agent__pb2.Agent.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.DeleteAgentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BanAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.BanAgent,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.BanAgentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AttestAgent': grpc.stream_stream_rpc_method_handler(
                    servicer.AttestAgent,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentRequest.FromString,
                    response_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentResponse.SerializeToString,
            ),
            'RenewAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewAgent,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentRequest.FromString,
                    response_serializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentResponse.SerializeToString,
            ),
            'CreateJoinToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJoinToken,
                    request_deserializer=spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CreateJoinTokenRequest.FromString,
                    response_serializer=spire_dot_api_dot_types_dot_jointoken__pb2.JoinToken.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spire.api.server.agent.v1.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/CountAgents',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsRequest.SerializeToString,
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CountAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/ListAgents',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsRequest.SerializeToString,
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.ListAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/GetAgent',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.GetAgentRequest.SerializeToString,
            spire_dot_api_dot_types_dot_agent__pb2.Agent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/DeleteAgent',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.DeleteAgentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BanAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/BanAgent',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.BanAgentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttestAgent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/spire.api.server.agent.v1.Agent/AttestAgent',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentRequest.SerializeToString,
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.AttestAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenewAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/RenewAgent',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentRequest.SerializeToString,
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.RenewAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateJoinToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.agent.v1.Agent/CreateJoinToken',
            spire_dot_api_dot_server_dot_agent_dot_v1_dot_agent__pb2.CreateJoinTokenRequest.SerializeToString,
            spire_dot_api_dot_types_dot_jointoken__pb2.JoinToken.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
