apiVersion: v1
kind: Service
metadata:
  name: argo-server-nodeport
spec:
  ports:
    - name: web
      port: 2746
      protocol: TCP
      targetPort: 2746
      nodePort: 30046
  selector:
    app: argo-server
  type: NodePort
