---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Istio
  - ../../../../components/vendor/kubeflow-manifests/common/istio-1-11/istio-crds/base
  - ../../../../components/vendor/kubeflow-manifests/common/istio-1-11/istio-namespace/base
  - ../../../../components/vendor/kubeflow-manifests/common/istio-1-11/istio-install/base

  # Cert-manager
  - ../../../../components/vendor/kubeflow-manifests/common/cert-manager/cert-manager/base

  # FL Suite
  - ../../base
