---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
data:
  k8s-workload-registrar.conf: |
    log_level = "debug"
    trust_domain = "katulu.io"
    server_socket_path = "/tmp/spire-server/private/api.sock"
    cluster = "local-k8s"
    pod_controller = true
    pod_label = "spire-workload"
    add_svc_dns_names = true
    mode = "crd"
    webhook_enabled = true
