apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
- spiffeids-crd.yaml

- certificate-authority.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-configmap.yaml
- server-service.yaml
- server-statefulset.yaml
- server-gateway.yaml
- server-virtualservice.yaml

- k8s-workload-configmap.yaml
- k8s-workload-registrar-cluster-role.yaml
- k8s-workload-registrar-service.yaml
- k8s-workload-registrar-validating-webhook-configuration.yaml
