apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "spire-server"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "katulu.io"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "local-k8s"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
        }
      }

      WorkloadAttestor "unix" {
          plugin_data {
          }
      }
    }
