---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebook-workspace
  labels:
    app: jupyter-notebook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
