---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: jupyter-notebook
  type: ClusterIP
