---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: container-registry

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: container-registry-config
    files:
      - config/config.yml

secretGenerator:
  - name: container-registry-auth
    files:
      # username: registry, password: registry
      - config/registry.htpasswd

generatorOptions:
  disableNameSuffixHash: true
