// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pkg/proto/fl_orchestrator.proto

package fl_orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperatorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OperatorMessage) Reset() {
	*x = OperatorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorMessage) ProtoMessage() {}

func (x *OperatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorMessage.ProtoReflect.Descriptor instead.
func (*OperatorMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{0}
}

type OrchestratorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*OrchestratorMessage_Tasks
	Message isOrchestratorMessage_Message `protobuf_oneof:"message"`
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (m *OrchestratorMessage) GetMessage() isOrchestratorMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *OrchestratorMessage) GetTasks() *OrchestratorMessage_TasksSpec {
	if x, ok := x.GetMessage().(*OrchestratorMessage_Tasks); ok {
		return x.Tasks
	}
	return nil
}

type isOrchestratorMessage_Message interface {
	isOrchestratorMessage_Message()
}

type OrchestratorMessage_Tasks struct {
	Tasks *OrchestratorMessage_TasksSpec `protobuf:"bytes,1,opt,name=tasks,proto3,oneof"`
}

func (*OrchestratorMessage_Tasks) isOrchestratorMessage_Message() {}

type OrchestratorMessage_ExecutorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Executor:
	//	*OrchestratorMessage_ExecutorSpec_OciExecutor
	//	*OrchestratorMessage_ExecutorSpec_CoremlExecutor
	//	*OrchestratorMessage_ExecutorSpec_TensorflowjsExecutor
	Executor isOrchestratorMessage_ExecutorSpec_Executor `protobuf_oneof:"executor"`
}

func (x *OrchestratorMessage_ExecutorSpec) Reset() {
	*x = OrchestratorMessage_ExecutorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_ExecutorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_ExecutorSpec) ProtoMessage() {}

func (x *OrchestratorMessage_ExecutorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_ExecutorSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_ExecutorSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 0}
}

func (m *OrchestratorMessage_ExecutorSpec) GetExecutor() isOrchestratorMessage_ExecutorSpec_Executor {
	if m != nil {
		return m.Executor
	}
	return nil
}

func (x *OrchestratorMessage_ExecutorSpec) GetOciExecutor() *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec {
	if x, ok := x.GetExecutor().(*OrchestratorMessage_ExecutorSpec_OciExecutor); ok {
		return x.OciExecutor
	}
	return nil
}

func (x *OrchestratorMessage_ExecutorSpec) GetCoremlExecutor() *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec {
	if x, ok := x.GetExecutor().(*OrchestratorMessage_ExecutorSpec_CoremlExecutor); ok {
		return x.CoremlExecutor
	}
	return nil
}

func (x *OrchestratorMessage_ExecutorSpec) GetTensorflowjsExecutor() *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec {
	if x, ok := x.GetExecutor().(*OrchestratorMessage_ExecutorSpec_TensorflowjsExecutor); ok {
		return x.TensorflowjsExecutor
	}
	return nil
}

type isOrchestratorMessage_ExecutorSpec_Executor interface {
	isOrchestratorMessage_ExecutorSpec_Executor()
}

type OrchestratorMessage_ExecutorSpec_OciExecutor struct {
	OciExecutor *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec `protobuf:"bytes,1,opt,name=oci_executor,json=ociExecutor,proto3,oneof"`
}

type OrchestratorMessage_ExecutorSpec_CoremlExecutor struct {
	CoremlExecutor *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec `protobuf:"bytes,2,opt,name=coreml_executor,json=coremlExecutor,proto3,oneof"`
}

type OrchestratorMessage_ExecutorSpec_TensorflowjsExecutor struct {
	TensorflowjsExecutor *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec `protobuf:"bytes,3,opt,name=tensorflowjs_executor,json=tensorflowjsExecutor,proto3,oneof"`
}

func (*OrchestratorMessage_ExecutorSpec_OciExecutor) isOrchestratorMessage_ExecutorSpec_Executor() {}

func (*OrchestratorMessage_ExecutorSpec_CoremlExecutor) isOrchestratorMessage_ExecutorSpec_Executor() {
}

func (*OrchestratorMessage_ExecutorSpec_TensorflowjsExecutor) isOrchestratorMessage_ExecutorSpec_Executor() {
}

type OrchestratorMessage_TaskSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique task identifier derived from the pipeline run and task id.
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Name of the workflow
	Workflow string `protobuf:"bytes,2,opt,name=Workflow,proto3" json:"Workflow,omitempty"`
	// Server name indication used to identify the aggreation server.
	SNI      string                            `protobuf:"bytes,3,opt,name=SNI,proto3" json:"SNI,omitempty"`
	Executor *OrchestratorMessage_ExecutorSpec `protobuf:"bytes,4,opt,name=executor,proto3" json:"executor,omitempty"`
}

func (x *OrchestratorMessage_TaskSpec) Reset() {
	*x = OrchestratorMessage_TaskSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_TaskSpec) ProtoMessage() {}

func (x *OrchestratorMessage_TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_TaskSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_TaskSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 1}
}

func (x *OrchestratorMessage_TaskSpec) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *OrchestratorMessage_TaskSpec) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *OrchestratorMessage_TaskSpec) GetSNI() string {
	if x != nil {
		return x.SNI
	}
	return ""
}

func (x *OrchestratorMessage_TaskSpec) GetExecutor() *OrchestratorMessage_ExecutorSpec {
	if x != nil {
		return x.Executor
	}
	return nil
}

type OrchestratorMessage_TasksSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*OrchestratorMessage_TaskSpec `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *OrchestratorMessage_TasksSpec) Reset() {
	*x = OrchestratorMessage_TasksSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_TasksSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_TasksSpec) ProtoMessage() {}

func (x *OrchestratorMessage_TasksSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_TasksSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_TasksSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 2}
}

func (x *OrchestratorMessage_TasksSpec) GetTasks() []*OrchestratorMessage_TaskSpec {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type OrchestratorMessage_ExecutorSpec_OCIExecutorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) Reset() {
	*x = OrchestratorMessage_ExecutorSpec_OCIExecutorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) ProtoMessage() {}

func (x *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_ExecutorSpec_OCIExecutorSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *OrchestratorMessage_ExecutorSpec_OCIExecutorSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) Reset() {
	*x = OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) ProtoMessage() {}

func (x *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) Reset() {
	*x = OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) ProtoMessage() {}

func (x *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_fl_orchestrator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) Descriptor() ([]byte, []int) {
	return file_pkg_proto_fl_orchestrator_proto_rawDescGZIP(), []int{1, 0, 2}
}

func (x *OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_pkg_proto_fl_orchestrator_proto protoreflect.FileDescriptor

var file_pkg_proto_fl_orchestrator_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x5f, 0x6f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xf4, 0x05, 0x0a, 0x13, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x05,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4f, 0x72,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x70, 0x65, 0x63, 0x48, 0x00, 0x52, 0x05, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x1a, 0xcd, 0x03, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x56, 0x0a, 0x0c, 0x6f, 0x63, 0x69, 0x5f, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x4f, 0x72,
	0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4f,
	0x43, 0x49, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x48, 0x00,
	0x52, 0x0b, 0x6f, 0x63, 0x69, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x5f, 0x0a,
	0x0f, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x6c, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x4d, 0x4c,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x48, 0x00, 0x52, 0x0e,
	0x63, 0x6f, 0x72, 0x65, 0x6d, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x71,
	0x0a, 0x15, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x6a, 0x73, 0x5f, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e,
	0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63,
	0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x4a, 0x53, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x48, 0x00, 0x52, 0x14, 0x74, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x6a, 0x73, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x1a, 0x27, 0x0a, 0x0f, 0x4f, 0x43, 0x49, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x2a, 0x0a, 0x12, 0x43, 0x6f,
	0x72, 0x65, 0x4d, 0x4c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x30, 0x0a, 0x18, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x4a, 0x53, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x1a, 0x87, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x4e, 0x49, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x4e, 0x49, 0x12,
	0x3d, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x1a, 0x40,
	0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x70, 0x65, 0x63, 0x12, 0x33, 0x0a, 0x05, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4f, 0x72, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x7a, 0x0a, 0x0e, 0x46,
	0x6c, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x32, 0x0a,
	0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x10, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x14, 0x2e, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x74, 0x75, 0x6c, 0x75, 0x2d, 0x69, 0x6f, 0x2f,
	0x66, 0x6c, 0x2f, 0x66, 0x6c, 0x2d, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x66, 0x6c, 0x5f, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_fl_orchestrator_proto_rawDescOnce sync.Once
	file_pkg_proto_fl_orchestrator_proto_rawDescData = file_pkg_proto_fl_orchestrator_proto_rawDesc
)

func file_pkg_proto_fl_orchestrator_proto_rawDescGZIP() []byte {
	file_pkg_proto_fl_orchestrator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_fl_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_fl_orchestrator_proto_rawDescData)
	})
	return file_pkg_proto_fl_orchestrator_proto_rawDescData
}

var file_pkg_proto_fl_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_fl_orchestrator_proto_goTypes = []interface{}{
	(*OperatorMessage)(nil),                                           // 0: OperatorMessage
	(*OrchestratorMessage)(nil),                                       // 1: OrchestratorMessage
	(*OrchestratorMessage_ExecutorSpec)(nil),                          // 2: OrchestratorMessage.ExecutorSpec
	(*OrchestratorMessage_TaskSpec)(nil),                              // 3: OrchestratorMessage.TaskSpec
	(*OrchestratorMessage_TasksSpec)(nil),                             // 4: OrchestratorMessage.TasksSpec
	(*OrchestratorMessage_ExecutorSpec_OCIExecutorSpec)(nil),          // 5: OrchestratorMessage.ExecutorSpec.OCIExecutorSpec
	(*OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec)(nil),       // 6: OrchestratorMessage.ExecutorSpec.CoreMLExecutorSpec
	(*OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec)(nil), // 7: OrchestratorMessage.ExecutorSpec.TensorflowJSExecutorSpec
}
var file_pkg_proto_fl_orchestrator_proto_depIdxs = []int32{
	4, // 0: OrchestratorMessage.tasks:type_name -> OrchestratorMessage.TasksSpec
	5, // 1: OrchestratorMessage.ExecutorSpec.oci_executor:type_name -> OrchestratorMessage.ExecutorSpec.OCIExecutorSpec
	6, // 2: OrchestratorMessage.ExecutorSpec.coreml_executor:type_name -> OrchestratorMessage.ExecutorSpec.CoreMLExecutorSpec
	7, // 3: OrchestratorMessage.ExecutorSpec.tensorflowjs_executor:type_name -> OrchestratorMessage.ExecutorSpec.TensorflowJSExecutorSpec
	2, // 4: OrchestratorMessage.TaskSpec.executor:type_name -> OrchestratorMessage.ExecutorSpec
	3, // 5: OrchestratorMessage.TasksSpec.tasks:type_name -> OrchestratorMessage.TaskSpec
	0, // 6: FlOrchestrator.Join:input_type -> OperatorMessage
	0, // 7: FlOrchestrator.GetTasks:input_type -> OperatorMessage
	1, // 8: FlOrchestrator.Join:output_type -> OrchestratorMessage
	1, // 9: FlOrchestrator.GetTasks:output_type -> OrchestratorMessage
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_fl_orchestrator_proto_init() }
func file_pkg_proto_fl_orchestrator_proto_init() {
	if File_pkg_proto_fl_orchestrator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_fl_orchestrator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_ExecutorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_TaskSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_TasksSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_ExecutorSpec_OCIExecutorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_ExecutorSpec_CoreMLExecutorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_fl_orchestrator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrchestratorMessage_ExecutorSpec_TensorflowJSExecutorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_fl_orchestrator_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OrchestratorMessage_Tasks)(nil),
	}
	file_pkg_proto_fl_orchestrator_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*OrchestratorMessage_ExecutorSpec_OciExecutor)(nil),
		(*OrchestratorMessage_ExecutorSpec_CoremlExecutor)(nil),
		(*OrchestratorMessage_ExecutorSpec_TensorflowjsExecutor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_fl_orchestrator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_fl_orchestrator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_fl_orchestrator_proto_depIdxs,
		MessageInfos:      file_pkg_proto_fl_orchestrator_proto_msgTypes,
	}.Build()
	File_pkg_proto_fl_orchestrator_proto = out.File
	file_pkg_proto_fl_orchestrator_proto_rawDesc = nil
	file_pkg_proto_fl_orchestrator_proto_goTypes = nil
	file_pkg_proto_fl_orchestrator_proto_depIdxs = nil
}
