apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: katulu-fl
resources:
- kustomize
commonLabels:
  app: fl-orchestrator
  app.kubernetes.io/component: fl-orchestrator
  app.kubernetes.io/name: fl-orchestrator
  kustomize.component: fl-orchestrator
