---
apiVersion: fl.katulu.io/v1alpha1
kind: FlOperator
metadata:
  name: floperator
spec:
  orchestrator-url: istio-ingressgateway.istio-system
  orchestrator-sni: fl-orchestrator.fl-suite
  orchestrator-port: 443
