---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/fl-operator/kustomize/samples
  - ../../../components/fl-operator
  - ../../../components/katulu-fl-namespace/kustomize
  - ../../../components/spire/kustomize/spire-agent
  - ../../../components/spire/kustomize/spire-namespace
