apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fl-notebook-pipelines-edit
subjects:
  - kind: ServiceAccount
    name: fl-notebook
roleRef:
  kind: ClusterRole
  name: kubeflow-pipelines-edit
  apiGroup: rbac.authorization.k8s.io
