---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../fl-operator/base
  - ../../../../components/spire/kustomize/spire-agent
  - ../../../../components/spire/kustomize/spire-namespace
